# Generated by Django 4.1 on 2024-02-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.TextField(choices=[('water', 'plumbing issues'), ('infra', 'infrastructure issues'), ('electrical', 'electrical issues'), ('social_justice', 'social_justice')], default=5),
        ),
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/issues/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_images', to='issues.issue'),
        ),
    ]
