# Generated by Django 4.1 on 2024-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_category_issue_image_alter_image_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.TextField(choices=[('water', 'plumbing issues'), ('infra', 'infrastructure issues'), ('electrical', 'electrical issues'), ('social_justice', 'social_justice')], default='infra'),
        ),
    ]
