# Generated by Django 4.1 on 2024-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=10, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='long',
            field=models.DecimalField(decimal_places=16, default=10, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.TextField(choices=[('water', 'plumbing issues'), ('infra', 'infrastructure issues'), ('electrical', 'electrical issues'), ('social_justice', 'social_justice'), ('other', 'other')], default='infra'),
        ),
    ]
