# Generated by Django 4.1 on 2024-02-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted by Authorities'), (3, 'In Process'), (4, 'Problem is fixed')], default=1),
        ),
    ]
