# Generated by Django 4.1 on 2024-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
